### ISSUE TITLE
Stopped working in Gnome 42

### ISSUE THREAD

**Issue by aantusahaa** [OpenBangla/OpenBangla-Keyboard#292] opened 2022-04-27 05:27 UTC
It's not working in gnome 42. It doesn't show the preview window or output Bangla characters either. I tried rebuilding and changing to a fixed layout but that didn't help. However, the only place it seems to be working is in the global search input. 

System:
OS: Manjaro Linux x86_64 
Branch: Testing
Kernel: 5.15.35-1-MANJARO 
DE: GNOME 42.0 
WM: Mutter 
DM: X11

**Comment by Riyadulmollick** [comment] 2022-04-30 10:21
I am using the openbangla keyboard in Gnome 42 without having this type of problem. I think it's more like a distro problem. Although you are using a testing brunch, I guess it has some problem in the ibus engine.

My system is
OS: Arch Linux (Gnome 42) & also tested in Fedora 36 beta (Gnome 42)
Branch: Stable
Display Manager: Wayland

**Comment by aantusahaa** [comment] 2022-05-01 04:37
I just checked on Wayland. It's working fine there. But the issue persists on Xorg. Could you please also check on Xorg?

**Comment by Riyadulmollick** [comment] 2022-05-01 17:45
I have checked on Xorg also. No issue found

**Comment by rashidi77** [comment] 2022-05-01 17:47
Can't reproduce the issue on Fedora Silverblue 36 (testing branch) (tested on Wayland).

**Comment by ShawonAshraf** [comment] 2022-05-16 21:48
Same issue on Fedora 36, Works in Global Search field but not in applications.

**Comment by ShawonAshraf** [comment] 2022-05-17 13:21
Okay seemed to have fixed it on Fedora 36 with GNOME 42 running on X11. (Should work on Wayland as well). 

Check `/home/user/.config/environment.d/imsettings-gtk.conf`

You should have both `GTK_IM_MODULE` and `XMODIFIERS=@im` set to `ibus`. 

```bash
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```

In my case the issue was that I had installed KDE a few weeks ago to try it out and the qt settings overwrote the gtk ones. Cleaned up old configs and edited the above mentioned file and after a reboot openbangla-keyboard was working just fine!

**Comment by Mr-M1M3** [comment] 2022-05-18 13:59
Confirmed this issue on Manjaro. It stopped working specially in firefox!

**Comment by ShawonAshraf** [comment] 2022-05-18 23:47
> I confirm this issue on Manjaro. It stopped working specially in firefox!

Can you check your imsettings? I'm suspecting that this has more to do with how Manjaro packaged Gnome42.

**Comment by Mr-M1M3** [comment] 2022-05-20 10:51
> 

How do I?

**Comment by ShawonAshraf** [comment] 2022-05-22 16:38
> > Can you check your imsettings?
> 
> How do I?

```bash
cat /home/user/.config/environment.d/imsettings-gtk.conf
# replace user with your username
```

**Comment by Mr-M1M3** [comment] 2022-05-22 17:14
> > > Can you check your imsettings?
> > 
> > 
> > How do I?
> 
> ```shell
> cat /home/user/.config/environment.d/imsettings-gtk.conf
> # replace user with your username
> ```
Seems like, that file doesn't exist. No wonder why I couldn't find anything on google!
```bash
cat: /home/mr-m1m3/.config/environment.d/imsettings-gtk.conf: No such file or directory
```

**Comment by ilham-daiee-muntahi** [comment] 2022-05-29 05:39
@aantusahaa @Mr-M1M3 I had the same issue. I'm also running Manjaro Gnome but on the stable branch. I found a fix. What I did was:

- Uninstalled OBK
- Ran `sudo pacman -Sy manjaro-asian-input-support-ibus`. (This automatically does the configuration needed for OBK)
- Reinstalled OBK

Tested on Wayland and Xorg. Hopefully it will help.

**Comment by aantusahaa** [comment] 2022-05-29 14:32
Thanks, @ilham-daiee-muntahi! That worked like a charm.

**Comment by Mr-M1M3** [comment] 2022-05-29 14:55
@ilham-daiee-muntahi Thanks! That worked! It took me a while to figure out what *OBK* is BTW.

**Comment by mominul** [comment] 2022-07-12 16:45
Thanks @ilham-daiee-muntahi for the help! :heart: 

Closing the issue as resolved.

**Closed by mominul** 2022-07-12 16:45 UTC
