### ISSUE TITLE
Forbidden error  for fedora 33 repo. [status code: 403]

### ISSUE THREAD

**Issue by smearumi** [OpenBangla/OpenBangla-Keyboard#220] opened 2021-05-12 15:16 UTC
openbangla                                                                                                                             4.9  B/s |  10  B     00:02    
Errors during downloading metadata for repository 'openbangla':
  - Status code: 403 for https://dl.bintray.com/openbangla/fedora/33/repodata/repomd.xml (IP: 52.43.16.165)
Error: Failed to download metadata for repo 'openbangla': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: openbangla

**Comment by Dyrimon** [comment] 2021-05-12 16:27
Bintray no longer exists. Duplicate of #214 
Related Discussion: #190 
[Openbangla blog post](https://openbangla.github.io/blog/bintray-notice/)

**Comment by mominul** [comment] 2021-05-13 10:31
As @Dyrimon has posted, we have already published [a blog post](https://openbangla.github.io/blog/bintray-notice/) regarding the problem and its fix, please follow those instructions to fix the problem you're facing.

**Closed by mominul** 2021-05-13 10:31 UTC
