### ISSUE TITLE
Problem in ANSI mode writing certain 'যুক্তাক্ষর'

### ISSUE THREAD

**Issue by asifakonjee** [OpenBangla/OpenBangla-Keyboard#356] opened 2023-10-31 04:40 UTC
First of all, Thanks a ton for this excellent piece of application. I am experimenting and installed the develop branch to test ANSI. I have found a word (যুক্তাক্ষর) that is not working properly. স + ন = স্ন যেমন: স্নেহ লেখা যাচ্ছে না। বিভিন্ন আনসি ফন্টে চেষ্টা করেছি, কিন্তু কাজ হচ্ছে না। Thank you again.

**Comment by mominul** [comment] 2023-11-02 12:40
Thanks for the appreciation 😄 Have you tested with the Kalpurush ANSI font?

**Comment by asifakonjee** [comment] 2023-11-12 17:42
Yes. It works with Kalpurush ANSI and some newer versions of fonts from Lipighar.

**Comment by mominul** [comment] 2023-11-14 20:10
@asifakonjee Then it's not a bug, as we don't support latest versions of Bijoy ANSI fonts. Only Bijoy2000 compatible fonts are supported aka Kalpurush ANSI, Siam Rupali ANSI and Lipighor alternative ANSI fonts. I am closing this issue for now, but please feel free to add further comments if you have! 😄

**Closed by mominul** 2023-11-14 20:10 UTC
